// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IEncounterSystem {
  function setMudscanWorldAddress(address newAddress) external;

  function throwBall() external;

  function flee() external;
}
